# Q1. DBSCAN Clustering

In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv("crime_data.csv")

In [3]:
data.head()

Unnamed: 0  Murder  Assault  UrbanPop  Rape
0     Alabama    13.2      236        58  21.2
1      Alaska    10.0      263        48  44.5
2     Arizona     8.1      294        80  31.0
3    Arkansas     8.8      190        50  19.5
4  California     9.0      276        91  40.6

In [4]:
# doing EDA

In [5]:
data.shape

(50, 5)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  50 non-null     object 
 1   Murder      50 non-null     float64
 2   Assault     50 non-null     int64  
 3   UrbanPop    50 non-null     int64  
 4   Rape        50 non-null     float64
dtypes: float64(2), int64(2), object(1)
memory usage: 2.1+ KB


In [7]:
data.isna().sum()

Unnamed: 0    0
Murder        0
Assault       0
UrbanPop      0
Rape          0
dtype: int64

In [8]:
data.describe()

Murder     Assault   UrbanPop       Rape
count  50.00000   50.000000  50.000000  50.000000
mean    7.78800  170.760000  65.540000  21.232000
std     4.35551   83.337661  14.474763   9.366385
min     0.80000   45.000000  32.000000   7.300000
25%     4.07500  109.000000  54.500000  15.075000
50%     7.25000  159.000000  66.000000  20.100000
75%    11.25000  249.000000  77.750000  26.175000
max    17.40000  337.000000  91.000000  46.000000

In [9]:
# renam the colunms

In [10]:
data0=data.rename(columns={'Unnamed: 0':'states','Murder':'murder','Assault':'assault','UrbanPop':'urbanpop','Rape':'rape'})

In [11]:
data0.head()

states  murder  assault  urbanpop  rape
0     Alabama    13.2      236        58  21.2
1      Alaska    10.0      263        48  44.5
2     Arizona     8.1      294        80  31.0
3    Arkansas     8.8      190        50  19.5
4  California     9.0      276        91  40.6

In [12]:
# using scaler for getting values in 0 to 1 scale

In [13]:
x=data0.iloc[:,1:]

In [14]:
from sklearn.preprocessing import MinMaxScaler

In [15]:
sc=MinMaxScaler()
st=sc.fit_transform(x)

In [16]:
st

array([[0.74698795, 0.65410959, 0.44067797, 0.35917313],
       [0.55421687, 0.74657534, 0.27118644, 0.96124031],
       [0.43975904, 0.85273973, 0.81355932, 0.6124031 ],
       [0.48192771, 0.49657534, 0.30508475, 0.31524548],
       [0.4939759 , 0.79109589, 1.        , 0.86046512],
       [0.42771084, 0.54452055, 0.77966102, 0.81136951],
       [0.15060241, 0.22260274, 0.76271186, 0.09819121],
       [0.30722892, 0.6609589 , 0.6779661 , 0.21963824],
       [0.87951807, 0.99315068, 0.81355932, 0.63565891],
       [1.        , 0.56849315, 0.47457627, 0.47803618],
       [0.27108434, 0.00342466, 0.86440678, 0.33333333],
       [0.10843373, 0.25684932, 0.37288136, 0.17829457],
       [0.57831325, 0.69863014, 0.86440678, 0.43152455],
       [0.38554217, 0.23287671, 0.55932203, 0.35400517],
       [0.08433735, 0.03767123, 0.42372881, 0.10335917],
       [0.31325301, 0.23972603, 0.57627119, 0.27648579],
       [0.53614458, 0.21917808, 0.33898305, 0.23255814],
       [0.87951807, 0.69863014,

In [17]:
type(st)

numpy.ndarray

In [18]:
be=pd.DataFrame(st)

In [19]:
# geting clustering done

In [20]:
from sklearn.cluster import DBSCAN

In [21]:
group=DBSCAN(eps=0.2,min_samples=3)

In [22]:
group.fit(be)

DBSCAN(eps=0.2, min_samples=3)

In [23]:
lib= group.labels_

In [24]:
lib

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  0, -1,  0,  0,  0, -1,
       -1,  0,  1, -1,  1,  0, -1, -1,  0,  0, -1,  0, -1,  1, -1, -1,  0,
        0,  0,  2,  0, -1, -1,  0, -1, -1,  2, -1,  0,  2,  0,  0,  0],
      dtype=int64)

In [25]:
pd.DataFrame(lib,columns=['cluster']).head()

cluster
0       -1
1       -1
2       -1
3       -1
4       -1

In [26]:
# redy to merge into main dataset

In [27]:
data0.insert (loc=0,column='cluster',value=lib)

In [28]:
data0.head()

cluster      states  murder  assault  urbanpop  rape
0       -1     Alabama    13.2      236        58  21.2
1       -1      Alaska    10.0      263        48  44.5
2       -1     Arizona     8.1      294        80  31.0
3       -1    Arkansas     8.8      190        50  19.5
4       -1  California     9.0      276        91  40.6

In [29]:
data0[data0['cluster']==0]

cluster         states  murder  assault  urbanpop  rape
11        0          Idaho     2.6      120        54  14.2
13        0        Indiana     7.2      113        65  21.0
14        0           Iowa     2.2       56        57  11.3
15        0         Kansas     6.0      115        66  18.0
18        0          Maine     2.1       83        51   7.8
22        0      Minnesota     2.7       72        66  14.9
25        0        Montana     6.0      109        53  16.4
26        0       Nebraska     4.3      102        62  16.5
28        0  New Hampshire     2.1       57        56   9.5
33        0   North Dakota     0.8       45        44   7.3
34        0           Ohio     7.3      120        75  21.4
35        0       Oklahoma     6.6      151        68  20.0
37        0   Pennsylvania     6.3      106        72  14.9
40        0   South Dakota     3.8       86        45  12.8
45        0       Virginia     8.5      156        63  20.7
47        0  West Virginia     5.7       81        39   9.3
48        0      Wisconsin     2.6       53        66  10.8
49        0        Wyoming     6.8      161        60  15.6

# Q2. Airline 

In [48]:
air=pd.read_excel('EastWestAirlines.xlsx',sheet_name='data')

In [49]:
air.head()

ID#  Balance  Qual_miles  cc1_miles  cc2_miles  cc3_miles  Bonus_miles  \
0    1    28143           0          1          1          1          174   
1    2    19244           0          1          1          1          215   
2    3    41354           0          1          1          1         4123   
3    4    14776           0          1          1          1          500   
4    5    97752           0          4          1          1        43300   

   Bonus_trans  Flight_miles_12mo  Flight_trans_12  Days_since_enroll  Award?  
0            1                  0                0               7000       0  
1            2                  0                0               6968       0  
2            4                  0                0               7034       0  
3            1                  0                0               6952       0  
4           26               2077                4               6935       1

In [50]:
air1=air.drop(columns=['ID#'])

In [51]:
air1.head()

Balance  Qual_miles  cc1_miles  cc2_miles  cc3_miles  Bonus_miles  \
0    28143           0          1          1          1          174   
1    19244           0          1          1          1          215   
2    41354           0          1          1          1         4123   
3    14776           0          1          1          1          500   
4    97752           0          4          1          1        43300   

   Bonus_trans  Flight_miles_12mo  Flight_trans_12  Days_since_enroll  Award?  
0            1                  0                0               7000       0  
1            2                  0                0               6968       0  
2            4                  0                0               7034       0  
3            1                  0                0               6952       0  
4           26               2077                4               6935       1

In [52]:
air1.shape

(3999, 11)

In [53]:
air1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3999 entries, 0 to 3998
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Balance            3999 non-null   int64
 1   Qual_miles         3999 non-null   int64
 2   cc1_miles          3999 non-null   int64
 3   cc2_miles          3999 non-null   int64
 4   cc3_miles          3999 non-null   int64
 5   Bonus_miles        3999 non-null   int64
 6   Bonus_trans        3999 non-null   int64
 7   Flight_miles_12mo  3999 non-null   int64
 8   Flight_trans_12    3999 non-null   int64
 9   Days_since_enroll  3999 non-null   int64
 10  Award?             3999 non-null   int64
dtypes: int64(11)
memory usage: 343.8 KB


In [54]:
from sklearn.preprocessing import MinMaxScaler

In [56]:
veg= MinMaxScaler()
non= veg.fit_transform(air)

In [57]:
non

array([[0.00000000e+00, 1.65077268e-02, 0.00000000e+00, ...,
        0.00000000e+00, 8.43742464e-01, 0.00000000e+00],
       [2.48756219e-04, 1.12878760e-02, 0.00000000e+00, ...,
        0.00000000e+00, 8.39884254e-01, 0.00000000e+00],
       [4.97512438e-04, 2.42568502e-02, 0.00000000e+00, ...,
        0.00000000e+00, 8.47841813e-01, 0.00000000e+00],
       ...,
       [9.99502488e-01, 4.31694976e-02, 0.00000000e+00, ...,
        0.00000000e+00, 1.68796721e-01, 1.00000000e+00],
       [9.99751244e-01, 3.22018866e-02, 0.00000000e+00, ...,
        1.88679245e-02, 1.68676151e-01, 0.00000000e+00],
       [1.00000000e+00, 1.76908304e-03, 0.00000000e+00, ...,
        0.00000000e+00, 1.68314444e-01, 0.00000000e+00]])

In [60]:
from sklearn.cluster import DBSCAN
zund=DBSCAN(eps=1,min_samples=4)
zund.fit(non)

DBSCAN(eps=1, min_samples=4)

In [61]:
zund.labels_

array([0, 0, 0, ..., 1, 0, 0], dtype=int64)

In [62]:
zund1=pd.DataFrame(zund.labels_)

In [63]:
zund1

0
0     0
1     0
2     0
3     0
4     1
...  ..
3994  1
3995  1
3996  1
3997  0
3998  0

[3999 rows x 1 columns]

In [64]:
from sklearn.metrics import silhouette_score
silhouette_score(air,zund1)

C:\Users\91832\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.12930574984706272